ProyectoIncaKancha/Controllers/InventarioController.cs
using ProyectoIncaKancha.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoIncaKancha.Controllers
{
    public class InventarioController : Controller
    {
        public IEnumerable<Categoria> ListadoDeCategorias()
        {
            List<Categoria> categorias = new List<Categoria>();

            using (SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                cn.Open();

                SqlCommand cmd = new SqlCommand("sp_listar_categoria", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataReader dr = cmd.ExecuteReader();

                while (dr.Read())
                {
                    categorias.Add(new Categoria()
                    {
                        IdCategoria = dr.GetInt32(dr.GetOrdinal("IdCategoria")),
                        NombreCategoria = dr.GetString(dr.GetOrdinal("NombreCategoria"))
                    });
                }

                dr.Close();
            }

            return categorias;
        }

        public ActionResult ListaCategorias()
        {
            return View(ListadoDeCategorias());
        }

        public string InsertarCategoria(Categoria reg)
        {
            string mensaje = "";

            using (SqlConnection cn = new SqlConnection(
                ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                try
                {
                    using (SqlCommand cmd = new SqlCommand("sp_insertar_categoria", cn))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;

                        cmd.Parameters.AddWithValue("@NombreCategoria", reg.NombreCategoria);

                        cn.Open();

                        int i = cmd.ExecuteNonQuery();

                        mensaje = $"Se ha insertado {i} categoría";
                    }
                }
                catch (Exception ex)
                {
                    mensaje = $"Error al insertar categoría: {ex.Message}";
                }
            }

            return mensaje;
        }

        public ActionResult CrearCategoria()
        {
            return View(new Categoria());
        }

        [HttpPost]
        public ActionResult CrearCategoria(Categoria reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }
            ViewBag.mensaje = InsertarCategoria(reg);
            return View(reg);
        }



        public string ActualizarCategoria(Categoria reg)
        {
            string mensaje = "";

            using (SqlConnection cn = new SqlConnection(
                ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                try
                {
                    using (SqlCommand cmd = new SqlCommand("sp_actualizar_categoria", cn))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;

                        cmd.Parameters.AddWithValue("@IdCategoria", reg.IdCategoria);
                        cmd.Parameters.AddWithValue("@NombreCategoria", reg.NombreCategoria);

                        cn.Open();

                        int i = cmd.ExecuteNonQuery();
                        mensaje = $"Se ha actualizado {i} registro";
                    }
                }
                catch (Exception ex) { mensaje = ex.Message; }
            }

            return mensaje;
        }

        public ActionResult EditCategoria(int id = 0)
        {
            Categoria reg = BuscarCategoria(id);

            if (reg == null)
            {
                return RedirectToAction("ListaCategorias");
            }

            return View(reg);
        }

        public Categoria BuscarCategoria(int id)
        {
            return ListadoDeCategorias().FirstOrDefault(m => m.IdCategoria == id);
        }

        [HttpPost]
        public ActionResult EditCategoria(Categoria reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }

            ViewBag.mensaje = ActualizarCategoria(reg);

            return View(reg);
        }

        public string EliminarCategoria(int id)
        {
            string mensaje = "";

            using (SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_eliminar_categoria", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@IdCategoria", id);

                    cn.Open();

                    int i = cmd.ExecuteNonQuery();

                    mensaje = $"Se ha eliminado {i} categoría";
                }
                catch (Exception ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    cn.Close();
                }
            }

            return mensaje;
        }

        [HttpPost]
        public ActionResult EliminarCategorias(int id)
        {
            ViewBag.Mensaje = EliminarCategoria(id);
            return RedirectToAction("ListaCategorias");
        }


        /**METODO PARA LISTAR PROVEEDORES**/
        public IEnumerable<Proveedor> ListadoDeProveedor()
        {
            List<Proveedor> proveedores = new List<Proveedor>();

            using (SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                cn.Open();

                SqlCommand cmd = new SqlCommand("sp_listar_proveedores", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataReader dr = cmd.ExecuteReader();

                while (dr.Read())
                {
                    proveedores.Add(new Proveedor()
                    {
                        IdProveedor = dr.GetInt32(dr.GetOrdinal("IdProveedor")),
                        NombreProveedor = dr.GetString(dr.GetOrdinal("NombreProveedor")),
                        direccion = dr.GetString(dr.GetOrdinal("direccion")),
                        Telefono = dr.GetString(dr.GetOrdinal("Telefono")),
                    });
                }

                dr.Close();
            }

            return proveedores;
        }

        public ActionResult ListaProvedores()
        {
            return View(ListadoDeProveedor());
        }

        public string InsertarProveedor(Proveedor reg)
        {
            string mensaje = "";

            using (SqlConnection cn = new SqlConnection(
                ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                try
                {
                    using (SqlCommand cmd = new SqlCommand("sp_insertar_proveedor", cn))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;

                        cmd.Parameters.AddWithValue("@NombreProveedor", reg.NombreProveedor);
                        cmd.Parameters.AddWithValue("@Direccion", reg.direccion);
                        cmd.Parameters.AddWithValue("@Telefono", reg.Telefono);

                        cn.Open();

                        int i = cmd.ExecuteNonQuery();

                        mensaje = $"Se ha insertado {i} proveedor";
                    }
                }
                catch (Exception ex)
                {
                    mensaje = $"Error al insertar proveedor: {ex.Message}";
                }
            }

            return mensaje;
        }

        public ActionResult CrearProveedor()
        {
            return View(new Proveedor());
        }

        [HttpPost]
        public ActionResult CrearProveedor(Proveedor reg)
        {
            if (!ModelState.IsValid)
            {
                return View(reg);
            }
            ViewBag.mensaje = InsertarProveedor(reg);
            return View(reg);
        }
        public string ActualizarProveedor(Proveedor reg)
        {
            string mensaje = "";

            using (SqlConnection cn = new SqlConnection(
                ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                try
                {
                    using (SqlCommand cmd = new SqlCommand("sp_actualizar_proveedor", cn))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;

                        cmd.Parameters.AddWithValue("@IdProveedor", reg.IdProveedor);
                        cmd.Parameters.AddWithValue("@NombreProveedor", reg.NombreProveedor);
                        cmd.Parameters.AddWithValue("@Direccion", reg.direccion);
                        cmd.Parameters.AddWithValue("@Telefono", reg.Telefono);

                        cn.Open();

                        int i = cmd.ExecuteNonQuery();
                        mensaje = $"Se ha actualizado {i} registro";
                    }
                }
                catch (Exception ex) { mensaje = ex.Message; }
            }

            return mensaje;
        }

        public ActionResult EditarProveedor(int id = 0)
        {
            Proveedor reg = BuscarProveedor(id);

            if (reg == null)
            {
                return RedirectToAction("ListaProvedores");
            }

            return View(reg);
        }

        public Proveedor BuscarProveedor(int id)
        {
            return ListadoDeProveedor().FirstOrDefault(m => m.IdProveedor == id);
        }

        [HttpPost]
        public ActionResult EditarProveedor(Proveedor reg)
        {
            if (!ModelState.IsValid)
            {

ProyectoIncaKancha/Views/Inventario/CrearCategoria.cshtml
@model ProyectoIncaKancha.Models.Categoria
@{
    ViewBag.Title = "CrearCategoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- SweetAlert2 CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.min.css">


<h2>CrearCategoria</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.NombreCategoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreCategoria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Nuevo", "CrearCategoria", null, new { @class = "btn btn-primary" })
                <input type="submit" value="Crear" class="btn btn-default" id="nuevoBtn" />
                @Html.ActionLink("Retornar", "ListaCategorias", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}
@ViewBag.mensaje


<!-- SweetAlert2 JS -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.all.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var nuevoBtn = document.getElementById('nuevoBtn');

        nuevoBtn.addEventListener('click', function (e) {
            e.preventDefault();

            Swal.fire({
                title: '¿Estás seguro de crear una nueva categoría?',
                text: 'Esta acción no se puede deshacer.',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#28a745',
                cancelButtonColor: '#6c757d',
                confirmButtonText: 'Sí, crear'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Si el usuario hace clic en "Sí, crear", envía el formulario
                    document.forms[0].submit();
                }
            });
        });
    });
</script>

ProyectoIncaKancha/Views/Inventario/CrearProducto.cshtml
@model ProyectoIncaKancha.Models.Producto
@{
    ViewBag.Title = "CrearProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CrearProducto</h2>

<!-- SweetAlert2 CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.min.css">


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NombreProducto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreProducto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreProducto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioUnitario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioUnitario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioUnitario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoria.IdCategoria, ViewBag.categorias as SelectList, new { @class = "form-select" })
                @Html.ValidationMessageFor(model => model.categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.proveedor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.proveedor.IdProveedor, ViewBag.proveedores as SelectList, new { @class = "form-select" })
                @Html.ValidationMessageFor(model => model.proveedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Nuevo", "CrearProducto", null, new { @class = "btn btn-primary" })
                <input type="submit" value="Create" class="btn btn-default" id="nuevoBtn"/>
                @Html.ActionLink("Retornar", "ListaProductos", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

<div>
    @ViewBag.mensaje
</div>


<!-- SweetAlert2 JS -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.all.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var nuevoBtn = document.getElementById('nuevoBtn');

        nuevoBtn.addEventListener('click', function (e) {
            e.preventDefault();

            Swal.fire({
                title: '¿Estás seguro de crear un nuevo producto?',
                text: 'Esta acción no se puede deshacer.',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#28a745',
                cancelButtonColor: '#6c757d',
                confirmButtonText: 'Sí, crear'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Si el usuario hace clic en "Sí, crear", envía el formulario
                    document.forms[0].submit();
                }
            });
        });
    });
</script>

ProyectoIncaKancha/Views/Inventario/CrearProveedor.cshtml
@model ProyectoIncaKancha.Models.Proveedor
@{
    ViewBag.Title = "CrearProveedor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- SweetAlert2 CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.min.css">


<h2>CrearProveedor</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Proveedor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.NombreProveedor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreProveedor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreProveedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Nuevo", "CrearProveedor", null, new { @class = "btn btn-primary" })
                <input type="submit" value="Crear" class="btn btn-default" id="nuevoBtn" />
                @Html.ActionLink("Retornar", "ListaProvedores", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}
@ViewBag.mensaje



<!-- SweetAlert2 JS -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.all.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var nuevoBtn = document.getElementById('nuevoBtn');

        nuevoBtn.addEventListener('click', function (e) {
            e.preventDefault();

            Swal.fire({
                title: '¿Estás seguro de crear un nuevo proveedor?',
                text: 'Esta acción no se puede deshacer.',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#28a745',
                cancelButtonColor: '#6c757d',
                confirmButtonText: 'Sí, crear'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Si el usuario hace clic en "Sí, crear", envía el formulario
                    document.forms[0].submit();
                }
            });
        });
    });
</script>

ProyectoIncaKancha/Views/Inventario/ListaCategorias.cshtml
@model IEnumerable<ProyectoIncaKancha.Models.Categoria>
@{
    ViewBag.Title = "ListaCategorias";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- SweetAlert2 CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.min.css">


<h2>ListaCategorias</h2>

<p>
    @Html.ActionLink("Create New", "CrearCategoria")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NombreCategoria)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCategoria)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditCategoria", new { id = item.IdCategoria }, new { @class = "btn btn-info btn-sm" }) |
                @using (Html.BeginForm("EliminarCategorias", "Inventario", new { id = item.IdCategoria }, FormMethod.Post, new { id = "eliminarForm" }))
                {
                    <input type="submit" value="Eliminar" class="btn btn-danger btn-sm eliminarBtn" data-id="@item.IdCategoria" />
                }
            </td>
        </tr>
    }

</table>

<!-- SweetAlert2 JS -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.all.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var botonesEliminar = document.querySelectorAll('.eliminarBtn');

        botonesEliminar.forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                e.preventDefault();
                var idProducto = this.getAttribute('data-id');

                Swal.fire({
                    title: '¿Estás seguro de eliminar esta categoria?',
                    text: 'Esta acción no se puede deshacer.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Sí, eliminar'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // Si el usuario hace clic en "Sí, eliminar", redirige a la acción de eliminar
                        document.getElementById('eliminarForm').action = '@Url.Action("EliminarCategorias", "Inventario")' + '/' + idProducto;
                        document.getElementById('eliminarForm').submit();
                    }
                });
            });
        });
    });
</script>

ProyectoIncaKancha/Views/Inventario/ListaProductos.cshtml
@model IEnumerable<ProyectoIncaKancha.Models.Producto>
@{
    ViewBag.Title = "ListaProductos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- SweetAlert2 CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.min.css">

<h2>Administración de Inventario</h2>

<p>
    @Html.ActionLink("Crear Nuevo Producto", "CrearProducto", null, new { @class = "btn btn-primary" })
</p>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Nombre del Producto</th>
                <th>Descripción</th>
                <th>Precio Unitario</th>
                <th>Stock</th>
                <th>Categoría</th>
                <th>Proveedor</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.NombreProducto)</td>
                    <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
                    <td>@Html.DisplayFor(modelItem => item.PrecioUnitario)</td>
                    <td>@Html.DisplayFor(modelItem => item.Stock)</td>
                    <td>@Html.DisplayFor(modelItem => item.categoria.NombreCategoria)</td>
                    <td>@Html.DisplayFor(modelItem => item.proveedor.NombreProveedor)</td>
                    <td>
                        @Html.ActionLink("Editar", "EditarProducto", new { id = item.id }, new { @class = "btn btn-info btn-sm" }) |
                        @using (Html.BeginForm("EliminarProductos", "Inventario", new { id = item.id }, FormMethod.Post, new { id = "eliminarForm" }))
                        {
                            <input type="submit" value="Eliminar" class="btn btn-danger btn-sm eliminarBtn" data-id="@item.id" />
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<p>Productos Existentes: @Model.Count()</p>

<!-- SweetAlert2 JS -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.all.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var botonesEliminar = document.querySelectorAll('.eliminarBtn');

        botonesEliminar.forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                e.preventDefault();
                var idProducto = this.getAttribute('data-id');

                Swal.fire({
                    title: '¿Estás seguro de eliminar este producto?',
                    text: 'Esta acción no se puede deshacer.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Sí, eliminar'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // Si el usuario hace clic en "Sí, eliminar", redirige a la acción de eliminar
                        document.getElementById('eliminarForm').action = '@Url.Action("EliminarProductos", "Inventario")' + '/' + idProducto;
                        document.getElementById('eliminarForm').submit();
                    }
                });
            });
        });
    });
</script>

ProyectoIncaKancha/Views/Inventario/ListaProvedores.cshtml
@model IEnumerable<ProyectoIncaKancha.Models.Proveedor>

@{
    ViewBag.Title = "ListaProveedores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- SweetAlert2 CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.min.css">


<h2>Lista de Proveedores</h2>

<p>
    @Html.ActionLink("Crear", "CrearProveedor")
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreProveedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreProveedor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.direccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefono)
                </td>
                <td>
                    @Html.ActionLink("Editar", "EditarProveedor", new { id = item.IdProveedor }, new { @class = "btn btn-info btn-sm" }),
                    @using (Html.BeginForm("EliminarProveedores", "Inventario", new { id = item.IdProveedor }, FormMethod.Post, new { id = "eliminarForm" }))
                    {
                        <input type="submit" value="Eliminar" class="btn btn-danger btn-sm eliminarBtn" data-id="@item.IdProveedor" />
                    }
                </td>

            </tr>
        }
    </tbody>
</table>


<!-- SweetAlert2 JS -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.all.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var botonesEliminar = document.querySelectorAll('.eliminarBtn');

        botonesEliminar.forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                e.preventDefault();
                var idProducto = this.getAttribute('data-id');

                Swal.fire({
                    title: '¿Estás seguro de eliminar este producto?',
                    text: 'Esta acción no se puede deshacer.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Sí, eliminar'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // Si el usuario hace clic en "Sí, eliminar", redirige a la acción de eliminar
                        document.getElementById('eliminarForm').action = '@Url.Action("EliminarProveedores", "Inventario")' + '/' + idProducto;
                        document.getElementById('eliminarForm').submit();
                    }
                });
            });
        });
    });
</script>