ProyectoIncaKancha/Controllers/AccesoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ProyectoIncaKancha.Models;
using ProyectoIncaKancha.Logica;
using System.Web.Security;

namespace ProyectoIncaKancha.Controllers
{
    public class AccesoController : Controller
    {
        // GET: Acceso
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string correo, string clave)
        {
            Usuarios objeto = new LO_Usuarios().EncontrarUsuario(correo, clave);

            if (objeto.Nombres != null)
            {


                FormsAuthentication.SetAuthCookie(objeto.Correo, false);

                Session["Usuario"] = objeto;

                return RedirectToAction("ListaProductos", "Inventario");
            }



            return View();
        }

    }
}

ProyectoIncaKancha/Views/Acceso/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    @Styles.Render("~/Content/Login.css")
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
                <div class="login-container">
                    <img src="~/img/avatar-img.png" alt="avatar" class="avatar-container">
                    <form action="@Url.Action("Login","Acceso")" method="post">
                        <h2>Bienvenido</h2>
                        <div class="input-div one">
                            <div class="i">
                                <i class="fas fa-user"></i>
                            </div>
                            <div>
                                <h6>Correo</h6>
                                <input class="input" type="email" name="correo" />
                            </div>
                        </div>
                        <div class="input-div two">
                            <div class="i">
                                <i class="fas fa-lock"></i>
                            </div>
                            <div>
                                <h6>Contraseña</h6>
                                <input class="input" type="password" name="clave" />
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success">Ingresar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    <script>
        const forms = document.querySelectorAll('input');

        function focusFuncion() {
            let parent = this.parentNode.parentNode;
            parent.classList.add('focus');
        }

        function quitarFuncion() {
            let parent = this.parentNode.parentNode;
            if (this.value == "") {
                parent.classList.remove('focus');
            }
        }

        forms.forEach(input => {
            input.addEventListener('focus', focusFuncion);
            input.addEventListener('blur', quitarFuncion);
        });
    </script>
</body>
</html>