ProyectoIncaKancha/Controllers/PersonalController.cs
using ProyectoIncaKancha.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoIncaKancha.Permisos;

namespace ProyectoIncaKancha.Controllers
{
    [PermisosRol(Models.Rol.Administrador)]
    public class PersonalController : Controller
    {
        public Usuarios buscar(string codigo)
        {
            if (int.TryParse(codigo, out int codigoInt))
            {
                return listadoDeUsuarios().FirstOrDefault(m => m.id == codigoInt);
            }
            else
            {
                return null;
            }
        }

        /**LISTAR USUARIOSS**/
        public IEnumerable<Usuarios> listadoDeUsuarios()
        {
            List<Usuarios> usuarios = new List<Usuarios>();

            using (SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                cn.Open();

                SqlCommand cmd = new SqlCommand("PListarUsuarios", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataReader dr = cmd.ExecuteReader();

                while (dr.Read())
                {
                    usuarios.Add(new Usuarios()
                    {
                        id = dr.GetInt32(dr.GetOrdinal("id")),
                        Nombres = dr.GetString(dr.GetOrdinal("Nombres")),
                        Apellidos = dr.GetString(dr.GetOrdinal("Apellidos")),
                        Correo = dr.GetString(dr.GetOrdinal("Correo")),
                        Clave = dr.GetString(dr.GetOrdinal("clave")),
                        Dni = dr.GetString(dr.GetOrdinal("Dni")),
                        IdRol = (Rol)dr.GetInt32(dr.GetOrdinal("IdRol"))
                    });
                }

                dr.Close();
            }

            return usuarios;
        }

        public ActionResult ListaUsuarios()
        {
            return View(listadoDeUsuarios());
        }
        /**INSERTAR USUARIOS**/
        public string InsertarUsuario(Usuarios reg)
        {
            string mensaje = "";

            using (SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_InsertarUsuario", cn);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@Nombres", reg.Nombres);
                    cmd.Parameters.AddWithValue("@Apellidos", reg.Apellidos);
                    cmd.Parameters.AddWithValue("@Correo", reg.Correo);
                    cmd.Parameters.AddWithValue("@Clave", reg.Clave);
                    cmd.Parameters.AddWithValue("@Dni", reg.Dni);
                    cmd.Parameters.AddWithValue("@IdRol", reg.IdRol);

                    cn.Open();

                    int i = cmd.ExecuteNonQuery();

                    mensaje = $"Se ha insertado {i} usuario";
                }
                catch (Exception ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    cn.Close();
                }
            }

            return mensaje;
        }

        public ActionResult Create()
        {
            return View(new Usuarios());
        }

        [HttpPost]
        public ActionResult Create(Usuarios reg)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Roles = new SelectList(Enum.GetValues(typeof(Rol)));
                return View(reg);
            }

            ViewBag.Mensaje = InsertarUsuario(reg);
            ViewBag.Roles = new SelectList(Enum.GetValues(typeof(Rol)));
            return View(reg);
        }

        /***EDITAR USUARIOS**/
        public string actualizar(Usuarios reg)
        {
            // Ejecuta el procedimiento almacenado y retorna el mensaje del proceso
            string mensaje = "";
            using (SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_ActualizarUsuario", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@Id", reg.id);
                    cmd.Parameters.AddWithValue("@Nombres", reg.Nombres);
                    cmd.Parameters.AddWithValue("@Apellidos", reg.Apellidos);
                    cmd.Parameters.AddWithValue("@Correo", reg.Correo);
                    cmd.Parameters.AddWithValue("@Clave", reg.Clave);
                    cmd.Parameters.AddWithValue("@Dni", reg.Dni);
                    cmd.Parameters.AddWithValue("@IdRol", reg.IdRol);

                    cn.Open();

                    int i = cmd.ExecuteNonQuery();
                    mensaje = $"Se ha actualizado {i} registro";
                }
                catch (Exception ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    cn.Close();
                }
            }
            return mensaje;
        }

        public ActionResult Edit(int? id)
        {

            if (!id.HasValue)
            {
                return RedirectToAction("Edit");
            }

            Usuarios reg = buscar(id.ToString());

            if (reg == null)
            {

                return RedirectToAction("Edit");
            }

            ViewBag.Roles = new SelectList(Enum.GetValues(typeof(Rol)));
            return View(reg);
        }
        [HttpPost]
        public ActionResult Edit(Usuarios reg)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Roles = new SelectList(Enum.GetValues(typeof(Rol)));
                return View(reg);
            }

            ViewBag.mensaje = actualizar(reg);
            ViewBag.Roles = new SelectList(Enum.GetValues(typeof(Rol)));

            return View(reg);
        }

        //METODOS PARA ELIMINAR EL USUARIO
        public string EliminarUsuario(int id)
        {
            string mensaje = "";

            using (SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["sql"].ConnectionString))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_EliminarUsuario", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@Id", id);

                    cn.Open();

                    int i = cmd.ExecuteNonQuery();

                    mensaje = $"Se ha eliminado {i} usuario";
                }
                catch (Exception ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    cn.Close();
                }
            }

            return mensaje;
        }

        [HttpPost]
        public ActionResult EliminarUsuarios(int id)
        {
            ViewBag.Mensaje = EliminarUsuario(id);
            return RedirectToAction("ListaUsuarios");
        }
    }
}

ProyectoIncaKancha/Views/Personal/Create.cshtml
@model ProyectoIncaKancha.Models.Usuarios
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- SweetAlert2 CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.min.css">


<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Clave, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Clave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dni, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dni, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dni, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdRol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.IdRol, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdRol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-offset-2 col-md-10">

            @Html.ActionLink("Nuevo", "Create", null, new { @class = "btn btn-primary" })

            <input type="submit" value="Create" class="btn btn-default" id="nuevoBtn"/>

            @Html.ActionLink("Retornar", "ListaUsuarios", null, new { @class = "btn btn-primary" })

        </div>
    </div>
}

@ViewBag.mensaje


<!-- SweetAlert2 JS -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.all.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var nuevoBtn = document.getElementById('nuevoBtn');

        nuevoBtn.addEventListener('click', function (e) {
            e.preventDefault();

            Swal.fire({
                title: '¿Estás seguro de crear un nuevo usuario?',
                text: 'Esta acción no se puede deshacer.',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#28a745',
                cancelButtonColor: '#6c757d',
                confirmButtonText: 'Sí, crear'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Si el usuario hace clic en "Sí, crear", envía el formulario
                    document.forms[0].submit();
                }
            });
        });
    });
</script>

ProyectoIncaKancha/Views/Personal/Edit.cshtml
@model ProyectoIncaKancha.Models.Usuarios
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <!-- SweetAlert2 CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.min.css">


    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Clave, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Clave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dni, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dni, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dni, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdRol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.IdRol, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdRol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" id="guardarBtn" />
            </div>
        </div>
    </div>
}
@ViewBag.mensaje
<div>
    @Html.ActionLink("Back to List", "ListaUsuarios")
</div>


<!-- SweetAlert2 JS -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.all.min.js"></script>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        var guardarBtn = document.getElementById('guardarBtn');

        guardarBtn.addEventListener('click', function (e) {
            e.preventDefault();

            Swal.fire({
                title: '¿Estás seguro de guardar los cambios?',
                text: 'Esta acción no se puede deshacer.',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#28a745',
                cancelButtonColor: '#6c757d',
                confirmButtonText: 'Sí, guardar'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Si el usuario hace clic en "Sí, guardar", envía el formulario
                    document.forms[0].submit();
                }
            });
        });
    });
</script>

ProyectoIncaKancha/Views/Personal/ListaUsuarios.cshtml
@model IEnumerable<ProyectoIncaKancha.Models.Usuarios>
@{
    ViewBag.Title = "ListaUsuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- SweetAlert2 CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.min.css">


<h2 style="text-align : center">Administracion de Personal</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellidos)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Correo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Clave)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dni)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdRol)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombres)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellidos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Clave)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dni)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdRol)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id })
                @using (Html.BeginForm("EliminarUsuarios", "Personal", new { id = item.id }, FormMethod.Post, new { id = "eliminarForm" }))
                {
                    <input type="submit" value="Eliminar" class="btn btn-danger btn-sm eliminarBtn" data-id="@item.id" />
                }
            </td>
        </tr>
    }

</table>

<div>
    Personal Registrado: @Model.Count()
</div>

<!-- SweetAlert2 JS -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.3/dist/sweetalert2.all.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var botonesEliminar = document.querySelectorAll('.eliminarBtn');

        botonesEliminar.forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                e.preventDefault();
                var idProducto = this.getAttribute('data-id');

                Swal.fire({
                    title: '¿Estás seguro de eliminar este producto?',
                    text: 'Esta acción no se puede deshacer.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Sí, eliminar'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // Si el usuario hace clic en "Sí, eliminar", redirige a la acción de eliminar
                        document.getElementById('eliminarForm').action = '@Url.Action("EliminarUsuarios", "Personal")' + '/' + idProducto;
                        document.getElementById('eliminarForm').submit();
                    }
                });
            });
        });
    });
</script>